[package]
name = "client-faucet"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
# until subxt supports better event decoding we need to include it as a dependency
client-identity = { path = "../../identity/client" }
codec = { version = "1.3.0", package = "parity-scale-codec" }
substrate-subxt = { version = "0.9.0", features = ["client"] }

[dev-dependencies]
async-std = { version = "=1.5.0", features = ["attributes"] }
test-client = { path = "../../bin/client", features = ["mock"] }
