[package]
name = "sunshine-chain-client"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
frame-support = "2.0.0-rc5"
parity-scale-codec = "1.3.4"
substrate-subxt = "0.10.1"
