[package]
name = "sunshine-chain-utils"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
parity-scale-codec = "1.3.4"
rand = "0.7.3"
sp-core = "2.0.0-rc5"
sp-trie = "2.0.0-rc5"
strobe-rs = "0.5.4"
thiserror = "1.0.20"
x25519-dalek = "0.6.0"
