[package]
name = "test-node"
version = "0.2.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.5"
log = "0.4.11"
structopt = "0.3.15"
parking_lot = "0.11.0"

sc-cli = "0.8.0-rc5"
sp-core = "2.0.0-rc5"
sc-executor = "0.8.0-rc5"
sc-service = "0.8.0-rc5"
sp-inherents = "2.0.0-rc5"
sc-transaction-pool = "2.0.0-rc5"
sp-transaction-pool = "2.0.0-rc5"
sc-network = "0.8.0-rc5"
sc-consensus-aura = "0.8.0-rc5"
sp-consensus-aura = "0.8.0-rc5"
sp-consensus = "0.8.0-rc5"
sc-consensus = "0.8.0-rc5"
sc-finality-grandpa = "0.8.0-rc5"
sp-finality-grandpa = "2.0.0-rc5"
sc-client-api = "2.0.0-rc5"
sp-runtime = "2.0.0-rc5"
sc-basic-authorship = "0.8.0-rc5"

test-runtime = { path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = "2.0.0-rc5"
