[package]
name = "test-cli"
version = "0.2.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
publish = false

[dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
clap = "3.0.0-beta.1"
dirs = "3.0.1"
env_logger = "0.7.1"
sunshine-client-utils = { path = "../../../sunshine-core/client" }
sunshine-faucet-cli = { path = "../../faucet/cli" }
sunshine-identity-cli = { path = "../../identity/cli" }
test-client = { path = "../client" }
