[package]
name = "test-cli"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
publish = false

[dependencies]
async-std = { version = "=1.5.0", features = ["attributes"] }
exitfailure = "0.5.1"
clap = "3.0.0-beta.1"
dirs = "3.0.1"
env_logger = "0.7.1"
ipfs-embed = "0.1.1"
keystore = { path = "../../keystore/substrate", package = "substrate-keybase-keystore" }
sled = "0.32.1"
substrate-subxt = "0.10.1"
sunshine-core = { path = "../../core" }
sunshine-faucet-cli = { path = "../../faucet/cli" }
sunshine-identity-cli = { path = "../../identity/cli" }
test-client = { path = "../client" }
